FROM node:18-alpine

WORKDIR /app/frontend

COPY Frontend/package*.json ./

RUN npm install

COPY Frontend/ .

RUN npm run build

FROM node:18-alpine

RUN npm install -g serve

WORKDIR /app

COPY --from=0 /app/frontend/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
